spring:
  application:
    name: xRoadExampleRestapiClient
  jmx:
    enabled: false
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

logging:
  level:
    ROOT: INFO
    com.nortal.xroad.restapi.client: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

application:
  xroad:
    timeout:
      connect-ms: 60000
      read-ms: 120000
