[versions]
jacoco = "0.8.14"
checkstyle = "10.26.1"
mapstruct = "1.6.3"
archunit = "1.4.1"

[libraries]
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
archunit-junit5-api = { module = "com.tngtech.archunit:archunit-junit5-api", version.ref = "archunit" }
archunit-junit5-engine = { module = "com.tngtech.archunit:archunit-junit5-engine", version.ref = "archunit" }

[plugins]
spring-boot = { id = "org.springframework.boot", version = "4.0.1" }
