name: xroad-rest-client
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Frontend configuration (build-time)
        VITE_MAX_HISTORY_ENTRIES: 25
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/actuator/health']
      interval: 5s
      timeout: 5s
      retries: 40
