name: xroad-client-101
services:
  app:
    image: ghcr.io/melbeltagy/x-road-client-101:latest
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/actuator/health']
      interval: 5s
      timeout: 5s
      retries: 40
